name: Build Ktor Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Gradle
        run: ./gradlew --no-daemon buildFatJar

      - name: Upload build artifacts
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: ktor-fat-jar
          path: build/libs/app.jar

      - name: Send GET request with artifact ID
        run: |
          curl -X GET "http://89.58.2.75:8000/webhook/strife-backend/${{ steps.artifact-upload-step.outputs.artifact-id }}"
