name: Build Ktor Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Gradle
        run: ./gradlew fatJar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ktor-fat-jar
          path: build/libs/app.jar
